nla/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('reg.urls')),
]

reg/urls.py
from django.conf.urls import url

from reg import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    # url(r'^register$', views.RegisterView.as_view(), name='register'),
    # url(r'^register/(?P<uuid>[\w]{8}-[\w]{4}-[\w]{4}-[\w]{4}-[\w]{12})/final',
    #     views.RegisterFinalView.as_view(),
    #     name='registerFinal'),
    url(r'^hotovo', views.hotovo, name='hotovo'),
    url(r'^motivacny_list', views.motivacny_example, name='motivacny_example'),
    url(r'media/(?P<file>.*)', views.upload, name='media'),
]#+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'reg.views.error_view'

reg/models.py
# -*- coding: utf-8 -*-
import uuid

from django.core.exceptions import ValidationError
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
# Create your models here.


def max_words(words=400):
    def validator(value):
        wslen = len(value.split())
        if wslen > words:
            raise ValidationError('Presiahnutý limit slov: %(current_words)s/%(max_words)s',
                                  params={'current_words': wslen, 'max_words': words},
                                  code='max_words')
    return validator


@python_2_unicode_compatible
class Registracia(models.Model):
    meno = models.CharField(max_length=100 )
    priezvisko = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    telefon = models.CharField(max_length=15)

    QUESTION_SOFT_LIMIT_WORDS = 200
    QUESTION_HARD_LIMIT_WORDS = 400

    uspech = models.TextField(validators=[max_words(QUESTION_HARD_LIMIT_WORDS)])
    smerovanie = models.TextField(validators=[max_words(QUESTION_HARD_LIMIT_WORDS)])
    okolie = models.TextField(validators=[max_words(QUESTION_HARD_LIMIT_WORDS)])
    ocakavanie = models.TextField(validators=[max_words(QUESTION_HARD_LIMIT_WORDS)])

    list = models.FileField(null=True, upload_to='uploads/list/')

    token = models.UUIDField(default=uuid.uuid4, editable=False)

    cv = models.FileField(upload_to='uploads/cv/', blank=True)

    ref = models.CharField(max_length=500)
    skola = models.CharField(max_length=500)

    STUPNE_STUDIA = (('1', 'Stredná škola',), ('2', 'Maturitný ročník',), ('3', 'Bakalárske štúdium',), ('4', 'Magisterské štúdium',), ('5', 'Absolvent (PhD.)',))
    stupen_studia = models.CharField(max_length=1, choices=STUPNE_STUDIA, null=True)

    udaje = models.BooleanField()
    novinky = models.BooleanField()

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.meno + ' ' + self.priezvisko

reg/forms.py
# coding=utf-8

from django.forms import ModelForm
from django import forms
from .models import Registracia
from django.core.exceptions import ValidationError


class RegistraciaForm(ModelForm):
    class Meta:
        model = Registracia

        STUPNE_STUDIA = (('1', 'Stredná škola',), ('2', 'Maturitný ročník',), ('3', 'Bakalárske štúdium',),
                         ('4', 'Magisterské štúdium',), ('5', 'Absolvent (PhD.)',))
        stupen_studia = forms.ChoiceField(widget=forms.Select(attrs={'id': 'mf-degree'}), choices=STUPNE_STUDIA)

        fields = ['meno', 'priezvisko', 'email', 'telefon', 'stupen_studia', 'ref', 'skola', 'udaje', 'novinky']

        widgets = {
            'meno': forms.TextInput(attrs={'placeholder': 'Meno'}),
            'priezvisko': forms.TextInput(attrs={'placeholder': 'Priezvisko'}),
            'email': forms.EmailInput(attrs={'placeholder': 'E-mail'}),
            'telefon': forms.TextInput(attrs={'placeholder': 'Telefónne číslo'}),
            'ref': forms.TextInput(attrs={'placeholder': 'Ako si sa o nás dozvedel/a'}),
            'skola': forms.TextInput(attrs={'placeholder': 'Názov aktuálnej školy'}),
            'udaje': forms.CheckboxInput(attrs={'required': True}),
            'novinky': forms.CheckboxInput(),
        }
        error_messages = {
            'meno': {
                'required': 'Položka meno je povinná.'
            },
            'priezvisko': {
                'required': 'Položka prievisko je povinná.'
            },
            'email': {
                'required': 'Položka email je povinná.'
            },
            'telefon': {
                'required': 'Položka telefónne číslo je povinná.'
            },
            'stupen_studia': {
                'required': 'Položka stupeň štúdia je povinná.'
            },
            'ref': {
                'required': 'Táto položka je povinná.',
            },
            'skola': {
                'required': 'Položka škola je povinná.',
            },
        }


class RegistraciaDruhyKrokForm(ModelForm):
    def clean_cv(self):
        cv = self.cleaned_data.get('cv', False)
        if cv:
            if cv._size > 2.5 * 1024 * 1024:
                raise ValidationError("CV súbor je príliš veľký ( > 2.5 MB )")
        else:
            raise ValidationError('Na dokončenie registrácie potrebujeme, aby si priložil svoj životopis.')
        return cv

    class Meta:
        model = Registracia

        cv = forms.FileField(label='CV')
        fields = ['cv', 'uspech', 'smerovanie', 'okolie', 'ocakavanie']

        widgets = {
            'uspech': forms.Textarea(attrs={
                'soft_limit': Registracia.QUESTION_SOFT_LIMIT_WORDS,
                'placeholder':
                    'Buď prosím konkrétny/a a pomenuj pokojne 2-3 situácie.'}),
            'smerovanie': forms.Textarea(attrs={
                'soft_limit': Registracia.QUESTION_SOFT_LIMIT_WORDS,
                'placeholder':
                    'Napíš nám, v akej oblasti alebo oblastiach sa chceš po/popri škole uplatniť. '
                    'Vlastné podnikanie, zamestnanie, neziskovka, verejný sektor? Alebo čokoľvek iné.'}),
            'okolie': forms.Textarea(attrs={
                'soft_limit': Registracia.QUESTION_SOFT_LIMIT_WORDS,
                'placeholder':
                    'Zaujíma nás, na ktorej téme/témach Ti záleží a ako konkrétne chceš prispieť '
                    '(alebo už prispievaš) k pozitívnej zmene svojho okolia.'}),
            'ocakavanie': forms.Textarea(attrs={
                'soft_limit': Registracia.QUESTION_SOFT_LIMIT_WORDS,
                'placeholder':
                    'Ako Ti vieme pomôcť, v čom sa chceš rozvíjať a ako by si to, čo u nás získaš, '
                    'vedel/a využiť vo svojom živote a v prospech svojho okolia.'}),
        }
        error_messages = {
            'uspech': {
                'max_words': 'Pokús sa prosím svoju myšlienku vyjadriť trochu stručnejšie.',
                'required': 'Na dokončenie registrácie potrebujeme od Teba odpovede na všetky otázky.',
            },
            'smerovanie': {
                'max_words': 'Pokús sa prosím svoju myšlienku vyjadriť trochu stručnejšie.',
                'required': 'Na dokončenie registrácie potrebujeme od Teba odpovede na všetky otázky.',
            },
            'okolie': {
                'max_words': 'Pokús sa prosím svoju myšlienku vyjadriť trochu stručnejšie.',
                'required': 'Na dokončenie registrácie potrebujeme od Teba odpovede na všetky otázky.',
            },
            'ocakavanie': {
                'max_words': 'Pokús sa prosím svoju myšlienku vyjadriť trochu stručnejšie.',
                'required': 'Na dokončenie registrácie potrebujeme od Teba odpovede na všetky otázky.',
            },
        }

reg/views.py
import os

from django.shortcuts import render, HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.conf import settings
from django.views.generic import View
from django.utils.encoding import smart_str

from infinario import Infinario

from reg.forms import RegistraciaForm, RegistraciaDruhyKrokForm
from reg.models import Registracia
# Create your views here.


def index(req):
    return render(req, "index.html")


class RegisterView(View):

    def get(self, req):
        form = RegistraciaForm()
        return render(req, "register_zaciatok.html", {'form': form})

    def post(self, req):
        form = RegistraciaForm(req.POST, req.FILES)
        if form.is_valid():
            form.save()
            if settings.EXPONEA_TRACK_REGISTRATION:
                client = Infinario(settings.EXPONEA_TOKEN, target=settings.EXPONEA_TARGET)

                client.identify(req.POST['email'])
                client.update({
                    'first_name': req.POST['meno'],
                    'last_name': req.POST['priezvisko'],
                    'email': req.POST['email'],
                    'token': str(form.instance.token)
                })
                client.track('registration_first_part')
            return HttpResponseRedirect(reverse('registerFinal', kwargs={'uuid': form.instance.token}))

        return render(req, "register_zaciatok.html", {'form':form})


class RegisterFinalView(View):
    def get(self, req, uuid):
        try:
            registracia = Registracia.objects.get(token=uuid)
        except Registracia.DoesNotExist:
            return HttpResponseRedirect(reverse('index'))

        form = RegistraciaDruhyKrokForm(instance=registracia)
        return render(req, "register_final.html", {'form': form})

    def post(self, req, uuid):
        try:
            registracia = Registracia.objects.get(token=req.POST.get("token", "x"))
        except Registracia.DoesNotExist:
            return HttpResponseRedirect(reverse('index'))

        form = RegistraciaDruhyKrokForm(req.POST, req.FILES, instance=registracia)
        if form.is_valid():
            form.save()
            if settings.EXPONEA_TRACK_REGISTRATION:
                client = Infinario(settings.EXPONEA_TOKEN, target=settings.EXPONEA_TARGET)
                client.identify(registracia.email)
                client.track('registration_documets_uploaded')
            return HttpResponseRedirect(reverse('hotovo'))
        return render(req, "register_final.html", {'form':form})


def hotovo(req):
    return render(req, "hotovo.html")


def motivacny_example(req):
    return render(req, "motivacny_example.html")


def error_view(req):
    return render(req, "error.html")


def upload(req, file):
    if req.user.is_authenticated():

        response = HttpResponse(mimetype='application/force-download')
        response['Content-Disposition'] = 'attachment; filename=%s' % smart_str(file)
        response['X-Sendfile'] = smart_str(os.path.join(settings.MEDIA_ROOT, file))
        # It's usually a good idea to set the 'Content-Length' header too.
        # You can also set any other required headers: Cache-Control, etc.
        return response
    else:
        return HttpResponseRedirect(reverse('index'))

reg/templates/hotovo.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load bootstrap3 %}
{% load staticfiles %}

{% block content %}
<div class="subpage-form">

<script type="text/javascript">
  $(function() {
     $("input:file").change(function (){
       $(this).addClass('picked');
     });
  });
</script>
	<section class="subpage-form-1">
    	<div class="wrapper">
        	<h1 class="underlined center">Skvelé!</h1>
            <p class="perex">Všetky informácie dorazili v poriadku.</p>
            <p class="perex">V blízkej dobe sa ti ozveme.</p>
            <p><img src="{% static 'images/graphic/great.png' %}" alt=""></p>
        </div>
    </section>
    <section class="subpage-form-3">
    	<div class="wrapper">
        	<h2 class="underlined center">V krátkosti o výberovom procese</h2>
            <p class="perex">Výberový proces je stupňovitý, to znamená, že po každom kole sa dozvieš, či postupuješ ďalej alebo nie.<br> Prvé výberové kolá začínajú v januári {{ settings.registration_year }}. Prihlášky registrujeme počas celého roka.</p>
            <div class="timeline">
            	<div class="start">
                	<p class="big">1.</p>
                    <p>bod</p>
                </div>
                <div class="zero">Zaslanie<br>prihlášky</div>
                <div class="line one">
                	<div class="point">
                    	<p class="little">1. kolo</p>
                        <p>Vyhodnotenie prihlášky,<br>CV a tvojej motivácie</p>
                    </div>
                </div>
                <div class="line two">
                	<div class="point">
                    	<p class="little">2. kolo</p>
                        <p>Prezentácia Nexterie<br>analytický test<br>10 minútové interview</p>
                    </div>
                </div>
                <div class="line three">
                	<div class="point">
                    	<p class="little">3. kolo</p>
                        <p>Skupinové diskusie</p>
                    </div>
                </div>
                <div class="line four">
                	<div class="point">
                    	<p class="little">4. kolo</p>
                        <p>Osobný pohovor</p>
                    </div>
                </div>
                <div class="last">
                	<p>Finálne rozhodnutie o prijatí / neprijatí</p>
                </div>
                <div class="cil">
                	<p><i class="fa fa-check"></i></p>
                </div>
            </div>
        </div>
    </section>
<section class="faq">
    <div class="wrapper">
    	<a href="http://nexteria.sk/som-student/ing/faq/" target="_blank">Často kladené otázky</a>
    </div>
</section>
</div>
{% endblock %}

reg/templates/motivacny_example.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load bootstrap3 %}
{% load staticfiles %}

{% block content %}
<div class="subpage-form">

<script type="text/javascript">
  $(function() {
     $("input:file").change(function (){
       $(this).addClass('picked');
     });
  });
</script>
	<section class="subpage-form-1">
    	<div class="wrapper">
            <img src="{% static 'images/graphic/motivacny_example.png' %}" class="motivacny-example" alt="">
        </div>
    </section>
    <section class="subpage-form-3">
    	<div class="wrapper">
        	<h2 class="underlined center">V krátkosti o výberovom procese</h2>
            <p class="perex">Výberový proces je stupňovitý, to znamená, že po každom kole sa dozvieš, či postupuješ ďalej alebo nie.<br> Prvé výberové kolá začínajú v januári {{ settings.registration_year }}. Prihlášky registrujeme počas celého roka.</p>
            <div class="timeline">
            	<div class="start">
                	<p class="big">1.</p>
                    <p>bod</p>
                </div>
                <div class="zero">Zaslanie<br>prihlášky</div>
                <div class="line one">
                	<div class="point">
                    	<p class="little">1. kolo</p>
                        <p>Vyhodnotenie prihlášky,<br>CV a tvojej motivácie</p>
                    </div>
                </div>
                <div class="line two">
                	<div class="point">
                    	<p class="little">2. kolo</p>
                        <p>Prezentácia Nexterie<br>analytický test<br>10 minútové interview</p>
                    </div>
                </div>
                <div class="line three">
                	<div class="point">
                    	<p class="little">3. kolo</p>
                        <p>Skupinové diskusie</p>
                    </div>
                </div>
                <div class="line four">
                	<div class="point">
                    	<p class="little">4. kolo</p>
                        <p>Osobný pohovor</p>
                    </div>
                </div>
                <div class="last">
                	<p>Finálne rozhodnutie o prijatí / neprijatí</p>
                </div>
                <div class="cil">
                	<p><i class="fa fa-check"></i></p>
                </div>
            </div>
        </div>
    </section>
<section class="faq">
    <div class="wrapper">
    	<a href="http://nexteria.sk/som-student/ing/faq/" target="_blank">Často kladené otázky</a>
    </div>
</section>
</div>
{% endblock %}

reg/templates/register_final.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load bootstrap3 %}
{% load staticfiles %}

{% block content %}
<div class="subpage-form">

<script type="text/javascript">
  $(function() {
     $("input:file").change(function (){
       $(this).addClass('picked');
     });
  });
</script>
	<section class="subpage-form-1">
    	<div class="wrapper">
        	<h1 class="underlined center">Dokončenie registrácie</h1>
            <p class="">Pre dokončenie registrácie potrebujeme tvoje CV a odpovede na nasledujúce otázky.</p>
            <p class=""><strong>Nasledujúce odpovede skús prosím formulovať čo najstručnejšie, každá by mala mať menej ako 200 slov.</strong></p>

        	<form class="main-form" id="reg_final" name="main-form" method="post" action="/register/{{ form.instance.token }}/final" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.non_field_errors }}

                <div class="form-line">
                    <strong>Kedy sa Ti podarilo prebrať iniciatívu a dosiahnuť úspech/výsledok, na ktorý si hrdý/á? <span class="mandatory-star">*</span></strong>
                    {{ form.uspech }}
                    <span class="text-counter"></span>
                    <span class="warning"></span>
                    {{ form.uspech.errors }}
                </div>
                <div class="form-line">
                    <strong>Kam smeruješ v najbližších rokoch? <span class="mandatory-star">*</span></strong>
                    {{ form.smerovanie }}
                    <span class="text-counter"></span>
                    {{ form.smerovanie.errors }}
                </div>
                <div class="form-line">
                    <strong>Ako chceš meniť svoje okolie k lepšiemu? <span class="mandatory-star">*</span></strong>
                    {{ form.okolie }}
                    <span class="text-counter"></span>
                    {{ form.okolie.errors }}
                </div>
                <div class="form-line">
                    <strong>Čo očakávaš od Nexteria Leadership Academy a ako to využiješ? <span class="mandatory-star">*</span></strong>
                    {{ form.ocakavanie }}
                    <span class="text-counter"></span>
                    {{ form.ocakavanie.errors }}
                </div>
            	<div class="row">
                    <input type="hidden" name="token" value="{{ form.instance.token }}" />
                    <div class="form-line half pull-left" id="cv">
                        <!--<input type="file" name="mf-cv" id="mf-cv" accept="application/pdf, image/*" required>-->
                        {{ form.cv }}
                        <!--<label for="mf-cv">Nahraj svoje CV<i class="fa fa-check"></i></label>-->
                        {{ form.cv.errors }}
                    </div>
                    <div class="form-line half extra pull-right">
                        <p>Vzor dobrého CV od šéfa slovenského Googlu, Rasťa Kulicha, nájdeš <a href="https://docs.google.com/presentation/d/1qs_GAM6UGr_HeEQPdF06Xf2RCqZTexvG0n_aWUD73eg/edit?usp=sharing" target="_blank">tu.</a></p>
                    </div>
                </div>
                <div class="form-line">
				    <input type="submit" class="button yellow" name="mf-submit" value="Dokončiť registráciu">
                </div>
            </form>

        </div>
    </section>
    <section class="subpage-form-3">
    	<div class="wrapper">
        	<h2 class="underlined center">V krátkosti o výberovom procese</h2>
            <p class="perex">Výberový proces je stupňovitý, to znamená, že po každom kole sa dozvieš, či postupuješ ďalej alebo nie.<br> Prvé výberové kolá začínajú v januári {{ settings.registration_yer }}. Prihlášky registrujeme počas celého roka.</p>
            <div class="timeline">
            	<div class="start">
                	<p class="big">1.</p>
                    <p>bod</p>
                </div>
                <div class="zero">Zaslanie<br>prihlášky</div>
                <div class="line one">
                	<div class="point">
                    	<p class="little">1. kolo</p>
                        <p>Vyhodnotenie prihlášky,<br>CV a tvojej motivácie</p>
                    </div>
                </div>
                <div class="line two">
                	<div class="point">
                    	<p class="little">2. kolo</p>
                        <p>Prezentácia Nexterie<br>analytický test<br>10 minútové interview</p>
                    </div>
                </div>
                <div class="line three">
                	<div class="point">
                    	<p class="little">3. kolo</p>
                        <p>Skupinové diskusie</p>
                    </div>
                </div>
                <div class="line four">
                	<div class="point">
                    	<p class="little">4. kolo</p>
                        <p>Osobný pohovor</p>
                    </div>
                </div>
                <div class="last">
                	<p>Finálne rozhodnutie o prijatí / neprijatí</p>
                </div>
                <div class="cil">
                	<p><i class="fa fa-check"></i></p>
                </div>
            </div>
        </div>
    </section>
<section class="faq">
    <div class="wrapper">
    	<a href="http://nexteria.sk/som-student/ing/faq/" target="_blank">Často kladené otázky</a>
    </div>
</section>
</div>
{% endblock %}

reg/templates/register_zaciatok.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load bootstrap3 %}
{% load staticfiles %}

{% block content %}
<div class="subpage-form">

<script type="text/javascript">
  $(function() {
     $("input:file").change(function (){
       $(this).addClass('picked');
     });
  });
</script>
	<section class="subpage-form-1">
    	<div class="wrapper">
        	<h1 class="underlined center">Teší nás tvoj záujem o Nexteria Leadership Academy</h1>
            <p class="perex">Sme radi, že máš záujem na sebe pracovať a zlepšovať sa! Nexteria Leadership Academy pripravujeme s úmyslom, aby na významných pozíciach boli slušní a schopní ľudia.</p>

        	<form class="main-form" name="main-form" method="post" action="{% url 'register' %}" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.non_field_errors }}

            	<div class="form-line half">
                	<span class="little">Meno <span class="mandatory-star">*</span></span>
                    {{ form.meno }}
                    {{ form.meno.errors }}
                </div>
                <div class="form-line half">
                	<span class="little">Priezvisko <span class="mandatory-star">*</span></span>
                    {{ form.priezvisko }}
                    {{ form.priezvisko.errors }}
                </div>
                <div class="form-line half">
                    <span class="little">Email <span class="mandatory-star">*</span></span>
                	{{ form.email }}
                    {{ form.email.errors }}
                </div>
                <div class="form-line half">
                    <span class="little">Telefónne číslo <span class="mandatory-star">*</span></span>
                	{{ form.telefon }}
                    {{ form.telefon.errors }}
                </div>
                <div>
                	<div class="form-line">
                        <span class="little">Ako si sa o nás dozvedel/a <span class="mandatory-star">*</span></span>
                    	<!--<input type="text" name="mf-ref" placeholder="Ako si sa o nás odzvedel" id="mf-ref">-->
                        {{ form.ref }}
                        {{ form.ref.errors }}
                    </div>
                    <div class="form-line half">
                        <span class="little">Názov aktuálnej školy <span class="mandatory-star">*</span></span>
                        <!--<input type="text" name="mf-school" placeholder="Názov školy" id="mf-school">-->
                        {{ form.skola }}
                        {{ form.skola.errors }}
                    </div>
                    <div class="form-line half">
                        <span class="little">Stupeň štúdia v máji {{ settings.registration_year }} <span class="mandatory-star">*</span></span>
                        {{ form.stupen_studia }}
                        {{ form.stupen_studia.errors }}
                    </div>
                </div>
                <div class="form-line check">
                    <!--<input type="checkbox" name="mf-suhlas" id="mf-suhlas" required>
                    <label for="mf-suhlas"><i class="fa fa-check"></i></label>-->
                    {{ form.udaje }}
                    <label for="id_udaje" id="id_udaje_label">
                        <span><a href="{% static 'suhlas2016.pdf' %}" target="_blank">Súhlas so spracovaním osobných údajov</a></span>
                    </label>
                    {{ form.udaje.errors }}
                </div>
                <div class="form-line check">
                    <!--<input type="checkbox" name="mf-subscribe" id="mf-subscribe">
                    <label for="mf-subscribe"><i class="fa fa-check"></i></label>-->
                    {{ form.novinky }}
                    <label for="id_novinky">
                        <span>Súhlas so zasielaním informačných materiálov</span>
                    </label>
                    {{ form.novinky.errors }}
                </div>
                <div class="form-line">
				    <input type="submit" class="button yellow" name="mf-submit" value="Pokračovať v registrácii">
                    <ul id="id_udaje_error" class="errorlist hidden"><li>Ak chcete pokračovať v registrácii, musíte súhlasiť so spracovaním osobných údajov.</li></ul>
                </div>

                <div class="form-line deadline">
                    Záverečný deadline na podanie prihlášky: <time datetime="2018-05-01">1. máj 2018</time>.
                </div>
                <div class="form-line">
                    V druhom kroku registrácie nám odpovedaj na otázky o tvojej motivácii a pošli svoje <a href="http://tiny.cc/nexteria-cv-manual" target="_blank">aktuálne CV</a>.
                </div>
            </form>

        </div>
    </section>
    <section class="subpage-form-3">
    	<div class="wrapper">
        	<h2 class="underlined center">V krátkosti o výberovom procese</h2>
            <p class="perex">Výberový proces je stupňovitý, to znamená, že po každom kole sa dozvieš, či postupuješ ďalej alebo nie.<br> Prvé výberové kolá začínajú v januári {{ settings.registration_year }}. Prihlášky registrujeme počas celého roka.</p>
            <div class="timeline">
            	<div class="start">
                	<p class="big">1.</p>
                    <p>bod</p>
                </div>
                <div class="zero">Zaslanie<br>prihlášky</div>
                <div class="line one">
                	<div class="point">
                    	<p class="little">1. kolo</p>
                        <p>Vyhodnotenie prihlášky,<br>CV a tvojej motivácie</p>
                    </div>
                </div>
                <div class="line two">
                	<div class="point">
                    	<p class="little">2. kolo</p>
                        <p>Prezentácia Nexterie<br>analytický test<br>10 minútové interview</p>
                    </div>
                </div>
                <div class="line three">
                	<div class="point">
                    	<p class="little">3. kolo</p>
                        <p>Skupinové diskusie</p>
                    </div>
                </div>
                <div class="line four">
                	<div class="point">
                    	<p class="little">4. kolo</p>
                        <p>Osobný pohovor</p>
                    </div>
                </div>
                <div class="last">
                	<p>Finálne rozhodnutie o prijatí / neprijatí</p>
                </div>
                <div class="cil">
                	<p><i class="fa fa-check"></i></p>
                </div>
            </div>
        </div>
    </section>
<section class="faq">
    <div class="wrapper">
    	<a href="http://nexteria.sk/som-student/ing/faq/" target="_blank">Často kladené otázky</a>
    </div>
</section>
</div>
{% endblock %}